---
docker_version: 1.6.0
docker_port: 2375
docker_compose_version: 1.3.0
docker_compose_path: ./bin/docker-compose
env_values:
  - { key: DOCKER_HOST, value: "tcp://localhost:{{ docker_port }}" }
  - { key: API_MOUNT_DIR, value: "/opt/app" }
  - { key: SWIFT_MOUNT_DIR, value: "/opt/swift" }
  - { key: PATH, value: "{{ ansible_env.PWD }}/bin:$PATH" }
